name: Build, Test and Publish tagged version

on:
  push:
    tags: ["v**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: build
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [build, test]
    secrets: inherit
    with:
      tags-policy: type=semver,pattern={{version}}
